"""
Serves pre-computed data-science outputs to the frontend.

All files are generated by the data-science pipeline
(watershield/data-science/src/export/geojson_builder.py and models/).
The backend reads them at request time so a fresh pipeline run is
immediately reflected without restarting the server.
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

router = APIRouter()

# Path from backend/ to data-science/data/outputs/
_OUTPUTS = Path(__file__).resolve().parents[2] / "data-science" / "data" / "outputs"


def _load(filename: str) -> dict | list:
    path = _OUTPUTS / filename
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"{filename} not found. Run the data-science pipeline first.",
        )
    with path.open(encoding="utf-8") as f:
        return json.load(f)


@router.get("/europe")
def get_europe_geojson():
    """
    Full GeoJSON FeatureCollection — 30 European cities + Wrocław.
    Each feature has wqi_current, risk_level, risk_color, trend, and metrics.
    Drop directly into MapLibre as a GeoJSON source.
    """
    return JSONResponse(content=_load("watershield_europe.geojson"))


@router.get("/wroclaw")
def get_wroclaw_geojson():
    """
    Wrocław-only GeoJSON — single feature with real Waterly sensor data.
    Includes anomaly_count_30d and live turbidity from MPWiK.
    """
    return JSONResponse(content=_load("watershield_wroclaw.geojson"))


@router.get("/summary")
def get_summary():
    """
    Quick stats across all monitored cities:
    total_cities, risk_counts, avg_wqi_by_country.
    """
    return _load("watershield_summary.json")


@router.get("/forecast")
def get_forecast():
    """
    30-day WQI forecast for Wrocław (Odra River).
    Each entry: date, wqi_predicted, wqi_lower, wqi_upper, risk_level.
    Winner model: XGBoost (7d RMSE = 11.9).
    """
    return _load("wqi_forecast_30d.json")


@router.get("/forecast-metrics")
def get_forecast_metrics():
    """
    Model evaluation metrics (Prophet vs XGBoost) for 7d and 30d horizons.
    Includes the winner model name and a caveats note.
    """
    return _load("forecast_metrics.json")
